### ISSUE TITLE
npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by poealone** [sparkandflash/next-js-airdrop-site#1]
`npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: NFTairdropapp@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8.6" from @chakra-ui/icons@1.1.7
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     @chakra-ui/icons@"^1.0.15" from the root project
npm ERR!   2 more (@emotion/react, @emotion/styled)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=18" from @chakra-ui/system@2.2.2
npm ERR! node_modules/@chakra-ui/system
npm ERR!   peer @chakra-ui/system@">=1.0.0" from @chakra-ui/icons@1.1.7
npm ERR!   node_modules/@chakra-ui/icons
npm ERR!     @chakra-ui/icons@"^1.0.15" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\johny\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johny\AppData\Local\npm-cache\_logs\2022-07-15T06_51_46_285Z-debug-0.log`

**Comment by poealone** [comment]
`0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\johny\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.14.0
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\johny\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\johny\OneDrive\Documents\GitHub\fayne_drop\.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\johny\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\johny\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install
23 verbose argv "install" "--location-global"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 3ms
27 verbose logfile logs-max:10 dir:C:\Users\johny\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\johny\AppData\Local\npm-cache\_logs\2022-07-15T06_58_32_487Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 21ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 9ms
38 timing idealTree:userRequests Completed in 0ms
39 silly idealTree buildDeps
40 silly fetch manifest @0x/subproviders@^6.6.1
41 http fetch GET 200 https://registry.npmjs.org/@0x%2fsubproviders 1152ms (cache revalidated)
42 silly fetch manifest @chakra-ui/icons@^1.0.15
43 http fetch GET 200 https://registry.npmjs.org/@chakra-ui%2ficons 1043ms (cache revalidated)
44 silly fetch manifest @chakra-ui/system@>=1.0.0
45 http fetch GET 200 https://registry.npmjs.org/@chakra-ui%2fsystem 720ms (cache revalidated)
46 silly fetch manifest @emotion/react@^11.4.1
47 http fetch GET 200 https://registry.npmjs.org/@emotion%2freact 702ms (cache revalidated)
48 silly fetch manifest @babel/core@^7.0.0
49 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 222ms (cache revalidated)
50 silly fetch manifest react@^17.0.2
51 http fetch GET 200 https://registry.npmjs.org/react 28ms (cache revalidated)
52 silly fetch manifest @emotion/styled@^11.3.0
53 http fetch GET 200 https://registry.npmjs.org/@emotion%2fstyled 915ms (cache revalidated)
54 silly fetch manifest react@>=18
55 timing idealTree Completed in 4831ms
56 timing command:install Completed in 4841ms
57 verbose stack Error: unable to resolve dependency tree
57 verbose stack     at Arborist.[failPeerConflict] (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1428:25)
57 verbose stack     at Arborist.[loadPeerSet] (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1421:30)
57 verbose stack     at async Arborist.[loadPeerSet] (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1362:11)
57 verbose stack     at async Arborist.[buildDepStep] (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:976:11)
57 verbose stack     at async Arborist.buildIdealTree (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
57 verbose stack     at async Promise.all (index 1)
57 verbose stack     at async Arborist.reify (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:154:5)
57 verbose stack     at async Install.exec (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:145:5)
57 verbose stack     at async module.exports (C:\Users\johny\AppData\Roaming\npm\node_modules\npm\lib\cli.js:78:5)
58 verbose cwd C:\Users\johny\OneDrive\Documents\GitHub\fayne_drop
59 verbose Windows_NT 10.0.19044
60 verbose node v16.16.0
61 verbose npm  v8.14.0
62 error code ERESOLVE
63 error ERESOLVE unable to resolve dependency tree
64 error
65 error While resolving: [1mNFTairdropapp[22m@[1m0.1.0[22m
65 error Found: [1mreact[22m@[1m17.0.2[22m[2m[22m
65 error [2mnode_modules/react[22m
65 error   [1mreact[22m@"[1m^17.0.2[22m" from the root project
65 error   [35mpeer[39m [1mreact[22m@"[1m>=16.8.6[22m" from [1m@chakra-ui/icons[22m@[1m1.1.7[22m[2m[22m
65 error   [2mnode_modules/@chakra-ui/icons[22m
65 error     [1m@chakra-ui/icons[22m@"[1m^1.0.15[22m" from the root project
65 error   2 more (@emotion/react, @emotion/styled)
65 error
65 error Could not resolve dependency:
65 error [35mpeer[39m [1mreact[22m@"[1m>=18[22m" from [1m@chakra-ui/system[22m@[1m2.2.2[22m[2m[22m
65 error [2mnode_modules/@chakra-ui/system[22m
65 error   [35mpeer[39m [1m@chakra-ui/system[22m@"[1m>=1.0.0[22m" from [1m@chakra-ui/icons[22m@[1m1.1.7[22m[2m[22m
65 error   [2mnode_modules/@chakra-ui/icons[22m
65 error     [1m@chakra-ui/icons[22m@"[1m^1.0.15[22m" from the root project
65 error
65 error Fix the upstream dependency conflict, or retry
65 error this command with --force, or --legacy-peer-deps
65 error to accept an incorrect (and potentially broken) dependency resolution.
65 error
65 error See C:\Users\johny\AppData\Local\npm-cache\eresolve-report.txt for a full report.
66 verbose exit 1
67 timing npm Completed in 4956ms
68 verbose unfinished npm timer reify 1657868312580
69 verbose unfinished npm timer reify:loadTrees 1657868312587
70 verbose unfinished npm timer idealTree:buildDeps 1657868312597
71 verbose unfinished npm timer idealTree:#root 1657868312597
72 verbose code 1
73 error A complete log of this run can be found in:
73 error     C:\Users\johny\AppData\Local\npm-cache\_logs\2022-07-15T06_58_32_487Z-debug-0.log
`

**Comment by sparkandflash** [comment]
try installing the packages one by one, I haven't updated it for quite some time

**Comment by srgoogle23** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
iuhhuh, @AliakbarETH, @Flodell12, @ntu-ben, @tripur3121, @Vivek-Murali, @Nitesh639, @soubhratra, @federico-daidone, @KurtzL, @ilisin, @alexcolls, @ArshavirH, @Nomadical1, @YellowC-137, @leejoonhun, @luongvantuit, @baocoo, @Big-Vi, @udaykiran-rupireddy
